<?php
/**
 * (c) Lex Kachan <lex.kachan@gmail.com>
 */

namespace UTI\Lib\Config;

/**
 * Stores configuration data.
 */
class Config
{
    //todo Real config class must be generated by script and cached for effective use.
//    CONFIG VARIABLES
    public static $APP_DIR;
    public static $APP_ENV;
    public static $URI_BASE;
    public static $APP_TMP;
    public static $APP_TPL_VIEW;
    public static $APP_TPL_PDF;
    public static $APP_SES;
    public static $APP_SES_DUR;
    public static $APP_LOG_EXC;
    public static $APP_PDF_IN;
    public static $APP_PDF_OUT;
    public static $APP_UPLOAD_DIR;
    public static $APP_IMG_DOC;
    public static $HTML_TYPE;
    public static $APP_STAGES_MIN;
    public static $APP_STAGES_MAX;
    public static $APP_RESULT;
//    CONFIG VARIABLES
}
